In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [2]:
df = pd.read_excel('ProjectDataMAXWS-3.xlsx')

In [3]:
df

,City,WD (name)1,WS1,WG1,WD (name)2,WS2,WG2,WD (name)3,WS3,WG3,WD (name),WS,WG,Storm Time (hrs.),Storm Month,Percentage Customers Affected
0,BRW,SW,67,117,NW,65,43,SW,54,72,SW,74,118,61.07,Feb,51.210884
1,BRW,E,54,56,S,59,50,SW,41,54,E,62,98,20.65,Feb,56.839002
2,BRW,NE,54,67,NE,46,65,NE,37,63,E,48,67,32.00,Apr,1.582766
3,BRW,W,57,85,SW,46,61,SW,33,50,W,67,89,24.00,May,0.090703
4,BRW,S,57,44,N,52,39,N,44,63,S,56,56,28.50,Sep,5.895692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,MAB,W,52,78,NW,80,95,N,89,121,NW,72,89,26.00,Jan,21.152738
446,MAB,S,61,80,S,74,95,SE,89,109,SE,100,128,20.00,Jan,2.622478
447,MAB,NW,44,65,NW,50,54,NE,39,46,NW,52,63,99.50,Feb,39.625360
448,MAB,S,63,107,W,57,69,S,96,115,S,65,100,16.00,Feb,56.887608
449,MAB,S,63,87,SE,61,83,SE,63,74,E,91,113,19.50,Apr,0.028818

In [4]:
df.describe()

,WS1,WG1,WS2,WG2,WS3,WG3,WS,WG,Storm Time (hrs.),Percentage Customers Affected
count,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000,450.000000
mean,56.075556,76.564444,57.266667,72.591111,53.488889,72.855556,56.382222,75.215556,31.282133,14.349644
std,12.609912,20.256409,13.478846,21.517733,19.385001,24.074754,14.132704,21.769193,21.233828,20.601825
min,31.000000,31.000000,31.000000,31.000000,30.000000,39.000000,30.000000,31.000000,13.500000,0.000000
25%,46.000000,61.000000,46.000000,54.000000,37.000000,54.000000,46.000000,59.000000,19.500000,0.117880
50%,56.000000,76.000000,57.000000,69.000000,50.000000,70.000000,56.000000,72.000000,25.500000,4.938406
75%,62.000000,89.000000,65.000000,93.000000,65.000000,83.000000,63.000000,89.000000,32.000000,22.217781
max,96.000000,121.000000,96.000000,121.000000,109.000000,150.000000,109.000000,150.000000,99.500000,100.000000

In [5]:
encoder = OneHotEncoder(handle_unknown='ignore')
encoder_df = pd.DataFrame(encoder.fit_transform(df[['City','Storm Month','WD (name)','WD (name)1','WD (name)2','WD (name)3']]).toarray())
final_df = df.join(encoder_df)

In [6]:
final_df

,City,WD (name)1,WS1,WG1,WD (name)2,WS2,WG2,WD (name)3,WS3,WG3,...,59,60,61,62,63,64,65,66,67,68
0,BRW,SW,67,117,NW,65,43,SW,54,72,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,BRW,E,54,56,S,59,50,SW,41,54,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,BRW,NE,54,67,NE,46,65,NE,37,63,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,BRW,W,57,85,SW,46,61,SW,33,50,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,BRW,S,57,44,N,52,39,N,44,63,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,MAB,W,52,78,NW,80,95,N,89,121,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
446,MAB,S,61,80,S,74,95,SE,89,109,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
447,MAB,NW,44,65,NW,50,54,NE,39,46,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
448,MAB,S,63,107,W,57,69,S,96,115,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
449,MAB,S,63,87,SE,61,83,SE,63,74,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [7]:
final_df = final_df.drop(['City','Storm Month','WD (name)','WD (name)1','WD (name)2','WD (name)3'], axis=1)

In [8]:
X = final_df.drop(['Percentage Customers Affected'], axis=1)
y = final_df['Percentage Customers Affected']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.21, random_state=0)

In [10]:
X_train_stand = X_train.copy()
X_test_stand = X_test.copy()


num_cols = ['WS','WG','WS1','WG1','WS2','WG2','WS3','WG3','Storm Time (hrs.)']


for i in num_cols:

    scale = StandardScaler().fit(X_train_stand[[i]])
    

    X_train_stand[i] = scale.transform(X_train_stand[[i]])

    X_test_stand[i] = scale.transform(X_test_stand[[i]])

In [11]:
from sklearn import preprocessing

In [12]:
y_train_stand = preprocessing.normalize([y_train])
y_train_stand = y_train_stand.T

In [13]:
y_train_stand

array([[7.60013015e-02],
       [6.85918918e-04],
       [1.24244921e-02],
       [1.41813249e-01],
       [1.66492431e-02],
       [2.29079931e-02],
       [8.25686788e-03],
       [2.11503085e-02],
       [4.79011431e-02],
       [2.77161747e-03],
       [1.34711889e-01],
       [1.72951415e-01],
       [1.81035301e-03],
       [0.00000000e+00],
       [9.70373529e-02],
       [1.50117114e-01],
       [0.00000000e+00],
       [9.91461355e-02],
       [2.72796464e-02],
       [7.15499663e-05],
       [5.03288419e-02],
       [4.43038193e-03],
       [6.69393405e-02],
       [6.33577677e-02],
       [2.30469328e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [8.06963433e-05],
       [0.00000000e+00],
       [1.81589345e-03],
       [2.33220346e-02],
       [1.65511397e-02],
       [1.05303996e-02],
       [5.82589471e-04],
       [6.46437119e-05],
       [5.49411361e-05],
       [6.46437119e-05],
       [0.00000000e+00],
       [0.00000000e+00],
       [2.45646105e-03],
       [1.16262343e-02],
       [5.89096097e-02],
       [7.63262893e-03],
       [1.80230331e-02],
       [2.33699474e-04],
       [1.68141954e-02],
       [2.65790321e-04],
       [5.55404273e-02],
       [1.27336561e-01],
       [2.24818451e-02],
       [0.00000000e+00],
       [5.53649677e-02],
       [3.35813922e-04],
       [4.26053127e-03],
       [5.55718259e-02],
       [5.45726849e-02],
       [1.74861185e-02],
       [5.18442569e-02],
       [2.18847807e-04],
       [8.61611895e-02],
       [0.00000000e+00],
       [1.83644913e-03],
       [0.00000000e+00],
       [5.94433112e-03],
       [1.62133212e-02],
       [2.33032930e-02],
       [5.65256830e-02],
       [1.65805272e-05],
       [4.75249130e-02],
       [3.30311130e-04],
       [4.97609718e-03],
       [9.33057548e-03],
       [1.89342443e-02],
       [3.18291378e-03],
       [3.70408978e-02],
       [6.62931320e-04],
       [4.41224792e-03],
       [2.11456237e-02],
       [1.86490884e-02],
       [4.87473542e-02],
       [3.09095854e-02],
       [6.57819245e-02],
       [4.09311464e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [9.60499772e-02],
       [8.15677739e-06],
       [5.82886984e-02],
       [1.30776042e-01],
       [7.86789348e-03],
       [1.88567131e-02],
       [3.35250558e-05],
       [4.31909271e-04],
       [1.57280136e-02],
       [7.43401342e-03],
       [2.41342440e-02],
       [5.76397681e-02],
       [4.22978814e-03],
       [1.14817798e-03],
       [4.51823108e-02],
       [0.00000000e+00],
       [5.22979152e-03],
       [9.71592903e-05],
       [1.40018280e-01],
       [1.01849119e-01],
       [2.22758895e-02],
       [1.04989489e-01],
       [0.00000000e+00],
       [1.54476424e-01],
       [3.30059269e-03],
       [5.47029504e-02],
       [1.54008174e-01],
       [2.04220256e-02],
       [4.03481717e-05],
       [2.55973471e-02],
       [1.49269026e-02],
       [0.00000000e+00],
       [2.66946488e-02],
       [6.68047120e-04],
       [8.63360710e-04],
       [0.00000000e+00],
       [3.43258973e-03],
       [8.77680544e-04],
       [2.18748780e-02],
       [8.12119518e-02],
       [1.44566171e-01],
       [1.00933874e-01],
       [1.20170449e-01],
       [0.00000000e+00],
       [1.34345564e-03],
       [5.32834801e-02],
       [1.49829537e-02],
       [5.33028281e-02],
       [1.66377522e-01],
       [7.49770978e-02],
       [9.95513163e-03],
       [4.97779880e-02],
       [1.11867168e-01],
       [2.20977107e-04],
       [2.10738501e-01],
       [1.38233708e-04],
       [1.56991073e-01],
       [4.76999775e-04],
       [3.33549826e-03],
       [4.05754092e-02],
       [2.36988188e-02],
       [6.93988553e-03],
       [0.00000000e+00],
       [0.00000000e+00],
       [1.48074732e-01],
       [4.78407493e-05],
       [0.00000000e+00],
       [3.04962961e-02],
       [2.81359814e-05],
       [0.00000000e+00],
       [9.72124026e-02],
       [1.03240337e-01],
       [9.70109613e-02],
       [3.59531789e-04],
       [2.12978546e-02],
       [1.51612341e-01],
       [1.55719060e-02],
       [3.25528257e-02],
       [1.76746502e-02],
       [2.89295333e-04],
       [7.16871371e-03],
       [0.00000000e+00],
       [3.84629230e-02],
       [8.91658364e-05],
       [2.44732907e-03],
       [5.43024441e-03],
       [4.76108426e-02],
       [3.24805944e-03],
       [2.42332990e-02],
       [4.45769624e-02],
       [5.82589471e-04],
       [7.77506571e-03],
       [2.29512634e-02],
       [1.29883729e-02],
       [1.20282441e-02],
       [1.13446547e-01],
       [4.95365758e-06],
       [9.56251669e-03],
       [1.05925358e-04],
       [8.35058900e-02],
       [1.94318581e-04],
       [2.05392664e-02],
       [1.21463113e-02],
       [9.99310155e-03],
       [1.09908969e-03],
       [2.97882662e-02],
       [0.00000000e+00],
       [1.35245798e-01],
       [2.11088167e-02],
       [1.35234852e-03],
       [2.19163131e-04],
       [0.00000000e+00],
       [1.16764984e-01],
       [3.70740588e-02],
       [3.52552642e-02],
       [3.69436326e-02],
       [7.66983295e-02],
       [1.68424358e-04],
       [2.22063752e-04],
       [1.91146032e-04],
       [3.92294144e-02],
       [0.00000000e+00],
       [2.25612193e-03],
       [8.82384402e-02],
       [0.00000000e+00],
       [8.97245513e-05],
       [0.00000000e+00],
       [2.10738501e-01],
       [3.22303133e-04],
       [1.26635084e-02],
       [8.12059122e-02],
       [2.46579380e-02],
       [1.25117173e-02],
       [7.49951538e-02],
       [1.76086088e-02],
       [1.40264404e-04],
       [3.38806342e-02],
       [1.75274605e-04],
       [0.00000000e+00],
       [2.92012956e-02],
       [7.25696104e-02],
       [0.00000000e+00],
       [1.35514437e-05],
       [1.08572128e-04],
       [2.80528808e-04],
       [7.77376437e-02],
       [3.34186052e-03],
       [0.00000000e+00],
       [1.10103710e-04],
       [1.04964126e-01],
       [1.06307952e-01],
       [1.20373879e-03],
       [2.29290427e-02],
       [7.59715598e-02],
       [2.10738501e-01],
       [2.12883494e-02],
       [1.09519148e-01],
       [0.00000000e+00],
       [1.07921050e-01],
       [1.15265687e-02],
       [1.87898685e-02],
       [1.08247400e-02],
       [9.96713703e-05],
       [5.84248685e-05],
       [3.62976594e-03],
       [2.77285194e-02],
       [0.00000000e+00],
       [0.00000000e+00],
       [5.44857316e-02],
       [7.20604096e-02],
       [8.06963433e-05],
       [0.00000000e+00],
       [2.65790321e-02],
       [1.95429831e-04],
       [3.17233931e-05],
       [6.44605607e-03],
       [7.99789257e-04],
       [1.26813634e-02],
       [7.14055875e-03],
       [0.00000000e+00],
       [1.93931136e-04],
       [4.66567667e-03],
       [3.85362984e-04],
       [6.35970308e-02],
       [1.15522396e-01],
       [1.19884092e-01],
       [2.10396606e-04],
       [1.08795367e-01],
       [9.18830382e-05],
       [1.05925358e-04],
       [1.34100223e-04],
       [1.89276938e-03],
       [2.91477871e-04],
       [3.77960822e-02],
       [0.00000000e+00],
       [6.19881001e-02],
       [9.76249624e-02],
       [1.01295413e-02],
       [1.07067563e-03],
       [1.39579870e-02],
       [6.46437119e-05],
       [4.55859313e-04],
       [7.78576005e-02],
       [4.16401493e-03],
       [9.79320595e-03],
       [1.42930785e-02],
       [4.66364593e-02],
       [1.29319158e-03],
       [3.23602507e-03],
       [1.67201077e-03],
       [8.39814509e-04],
       [1.35514437e-05],
       [2.13699769e-04],
       [0.00000000e+00],
       [9.90928759e-02],
       [6.77339681e-03],
       [4.81249866e-03],
       [5.26662104e-02],
       [5.97152941e-03],
       [1.42811175e-02],
       [4.97415816e-05],
       [2.89241467e-02],
       [3.04802856e-02],
       [4.96079766e-03],
       [2.05508592e-02],
       [1.83527491e-03],
       [0.00000000e+00],
       [9.62131277e-02],
       [3.81606730e-03],
       [2.06561371e-03],
       [4.33586506e-02],
       [1.18143518e-03],
       [2.04617465e-01],
       [1.07343190e-02],
       [3.26552358e-02],
       [1.05744644e-05],
       [0.00000000e+00],
       [3.83722578e-02],
       [4.80835289e-04],
       [1.32239113e-03],
       [2.42627642e-04],
       [4.50599398e-03],
       [1.16517894e-03],
       [6.08297329e-02],
       [1.90084410e-02],
       [1.65427504e-03],
       [1.28056764e-02],
       [5.11217599e-02],
       [2.21293371e-02],
       [1.05164763e-02],
       [2.77944648e-03],
       [1.50593131e-02],
       [3.06180795e-02],
       [2.75977987e-02],
       [1.16936155e-02],
       [2.00198927e-02],
       [4.68830713e-02],
       [5.98101561e-02],
       [5.31571702e-02],
       [2.05716938e-03],
       [4.60779027e-05],
       [9.55730162e-06],
       [3.22603870e-02],
       [7.15103507e-03],
       [3.66098040e-02],
       [0.00000000e+00],
       [1.50022823e-02],
       [1.02977692e-02],
       [1.97601273e-03],
       [2.21782777e-02]])

In [14]:
y_test_stand = preprocessing.normalize([y_test])
y_test_stand = y_test_stand.T

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
rf = RandomForestRegressor()
rf.fit(X_train_stand,y_train_stand)

C:\Users\Mufaddal\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\Mufaddal\AppData\Local\Temp\ipykernel_18048\3747747464.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train_stand,y_train_stand)

RandomForestRegressor()

In [17]:
pred = rf.predict(X_test_stand)

C:\Users\Mufaddal\anaconda3\envs\mlenv\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(

In [18]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

In [19]:
mean_absolute_error(pred, y_test_stand)

0.049985805494777324

In [20]:
a=X_train_stand.iloc[2].to_dict()

In [21]:
b=[v for i,v in a.items()]

In [22]:
b

[0.029279129779244326,
 -1.6052430818226884,
 -0.4024809596195907,
 -1.5617012015157232,
 -0.5111932417864637,
 -0.4293663763770997,
 -0.06005632604456326,
 -0.8741625751201483,
 -0.15488396708315275,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [23]:
d=rf.predict([b])

In [24]:
d

array([0.01161399])

In [25]:
out = pd.DataFrame(pred)

In [26]:
# out.to_excel('output.xlsx', index=False)